Ext.define('NeqMobile.controller.Home', {
    extend : 'Ext.app.Controller',
    views : ['Main','patient.List'],
    models : ['Patient'],
    stores : ['Patients'],
    refs : [


        {   ref       : 'mainview',
            selector  : 'Main',
            xtype     : 'Main',
            autoCreate: true}

    ],

    init : function() {
        console.log('Init home controller');
        
     this.getMainView().create();


        this.control({
            // example of listening to *all* button taps
 // Add a listener to the  searches store, so when it loads we can call our own method



            'button' : {
                'tap' : function() {
                    console.log('There are'
                        + this.getPatientsStore()
                        .getTotalCount()
                        + 'records');
                    var bla = Ext.ComponentQuery.query('list');
                    bla[0].setStore(this.getPatientsStore());
                    bla[0].refresh();
                }
            }
        });

    },
     onSearchesStoreLoad: function() {
        var searchList    = this.getSearchList(),
            searchesStore = this.getSearchesStore(),
            profile       = this.getProfile(),
            model;

        model = searchesStore.getAt(0);
        if (model && profile != "phone") {
            searchList.select(model);
        }
    },



    onLaunch : function() {
        console.log('onLaunch home controller');
        // The "getter" here was generated by specifying the
        // stores array (above)
        var stationsStore = this.getPatientsStore();
//
//				stationsStore.load({
//							callback : this.onStationsLoad,
//							scope : this
//						});
    },

    onStationsLoad : function() {
        this.getPatientsList().setStore(this.getPatientsStore());
    },

    onButtonClick : function() {
        alert('button clicked')
    }
});