Ext.define('NeqMobile.controller.Home', {
    extend : 'Ext.app.Controller',
    requires: ['NeqMobile.view.login.LoginForm','NeqMobile.view.Main','NeqMobile.view.PatientOverview'],
    views : ['Main','patient.List','patient.Dashboard','Testpanel','login.LoginForm','PatientOverview','Workarea'],
    models : ['Patient','UserLoginData'],
    stores : ['Patients','Users'],
    refs : [
        {   ref       : 'mainview',
            selector  : 'Main',
            xtype     : 'Main',
            autoCreate: true},
        { ref: 'mybutton',
            selector : 'button'},
        { ref: 'mytestpanel',
            selector : 'testpanel'},
        {   ref       : 'loginform',
            selector  : 'loginform'},
        { ref: 'patientoverview',
            selector: 'patientoverview',
        autoCreate: true},
        { ref: 'workarea',
            selector : 'workarea'}
    ],

    init : function() {


        //   Ext.ComponentQuery.query('loginform').down('button').setHandler(this.onLoginSuccess);


        console.log('Init home controller');
        var myMainView = this.getMainView().create();
        this.myview = myMainView;

        this.control({
            // example of listening to *all* button taps
            'button': { 'tap': this.onLoginSuccess

            }});

//            // example of listening to *all* button taps
//            // Add a listener to the  searches store, so when it loads we can call our own method
//
//
//
//
//
//
//                'tap' : function() {
//
//
//                    var mypanel = Ext.widget('testpanel');
//
//
//                    //  Ext.Viewport.setActiveItem(mypanel);
//                    console.log('son muell');
//                    console.log('There are'
//                        + this.getPatientsStore()
//                        .getTotalCount()
//                        + 'records');
//                    var bla = Ext.ComponentQuery.query('list');
//                    bla[0].setStore(this.getPatientsStore());
//                    bla[0].refresh();
//                }
//            }
//        });

//    },
//    onSearchesStoreLoad: function() {
//        var searchList = this.getSearchList(),
//            searchesStore = this.getSearchesStore(),
//            profile = this.getProfile(),
//            model;
//
//        model = searchesStore.getAt(0);
//        if (model && profile != "phone") {
//            searchList.select(model);
//        }
//    },
//
//
//
//    onLaunch : function() {
//        console.log('onLaunch home controller');
//        // The "getter" here was generated by specifying the
//        // stores array (above)
//        var stationsStore = this.getPatientsStore();
////
////				stationsStore.load({
////							callback : this.onStationsLoad,
////							scope : this
////						});
//    },
//
//    onStationsLoad : function() {
//        this.getPatientsList().setStore(this.getPatientsStore());
//    },
//
//    onButtonClick : function() {
//        alert('button clicked')
//    }
    },


    onLoginSuccess: function (user, session) {
      var patientoverview = this.getPatientOverviewView().create();
     this.Workarea.add(patientoverview);
    this.Workarea.setActiveItem(1);

    }


});